<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIPbO84Z\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIPbO84Z/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerIPbO84Z.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerIPbO84Z\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerIPbO84Z\App_KernelProdContainer([
    'container.build_hash' => 'IPbO84Z',
    'container.build_id' => '209678ce',
    'container.build_time' => 1657215806,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIPbO84Z');
