<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHvCKt6w\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHvCKt6w/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHvCKt6w.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHvCKt6w\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHvCKt6w\App_KernelDevDebugContainer([
    'container.build_hash' => 'HvCKt6w',
    'container.build_id' => '07b589b2',
    'container.build_time' => 1662533892,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHvCKt6w');
